trigger:
  branches:
    include:
      - master
pool:
  name: Default
  demands: java

steps:
  - task: SonarSource.sonarcloud.14d9cde6-c1da-4d55-aa01-2965cd301255.SonarCloudPrepare@1
    displayName: 'Prepare analysis on SonarCloud'
    inputs:
      SonarCloud: SonarCloud
      organization: oscarvallejo
      scannerMode: Other
      extraProperties: |
        # Additional properties that will be passed to the scanner,
        # Put one key=value per line, example:
        # sonar.exclusions=**/*.bin
        sonar.projectKey=OscarVallejo_ETB-Demo
        sonar.projectName=ETB Demo

  - task: Gradle@2
    displayName: 'gradlew build'
    inputs:
      gradleWrapperFile: 'gradlew'
      jdkVersionOption: 1.11
      sonarQubeRunAnalysis: true
      sonarQubeGradlePluginVersion: 3.3

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: '$(system.defaultworkingdirectory)'
      Contents: '**/*.jar'
      TargetFolder: '$(build.artifactstagingdirectory)'
    enabled: false
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    enabled: false
    condition: succeededOrFailed()

  - task: SonarSource.sonarcloud.38b27399-a642-40af-bb7d-9971f69712e8.SonarCloudPublish@1
    displayName: 'Publish Quality Gate Result'

  - task: SimondeLang.sonarcloud-buildbreaker.sonar-buildbreaker.sonarcloud-buildbreaker@2
    displayName: 'Break build on quality gate failure'
    inputs:
      SonarCloud: SonarCloud
      organization: oscarvallejo

